version: '3.8'

services:
  web:
    image: ghcr.io/shaunnorris/solent-marks-calculator:latest
    container_name: bearings-app
    restart: unless-stopped
    ports:
      - "${WEB_HOST_PORT:-8000}:8000"
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID:-placeholder}

networks:
  app-network:
    driver: bridge
